version: '2'
services:
    websocketdemo-app:
        image: websocketdemo
        external_links:
            - websocketdemo-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/websocketdemo
        ports:
            - 8080:8080
    websocketdemo-postgresql:
        extends:
            file: postgresql.yml
            service: websocketdemo-postgresql
